#!/usr/bin/env awk -f
BEGIN {
  # PEOPLE
  emoji["smile"]="\xf0\x9f\x98\x84";
  emoji["smiley"]="\xf0\x9f\x98\x83"
  emoji["grinning"]="\xf0\x9f\x98\x80";
  emoji["blush"]="\xf0\x9f\x98\x8a";
  emoji["relaxed"]="\xe2\x98\xba\xef\xb8\x8f";
  emoji["wink"]="\xf0\x9f\x98\x89";
  emoji["heart_eyes"]="\xf0\x9f\x98\x8d";
  emoji["kissing_heart"]="\xf0\x9f\x98\x98";
  emoji["kissing_closed_eyes"]="\xf0\x9f\x98\x9a";
  emoji["kissing"]="\xf0\x9f\x98\x97";
  emoji["kissing_smiling_eyes"]="\xf0\x9f\x98\x99";
  emoji["stuck_out_tongue_winking_eye"]="\xf0\x9f\x98\x9c";
  emoji["stuck_out_tongue_closed_eyes"]="\xf0\x9f\x98\x9d";
  emoji["stuck_out_tongue"]="\xf0\x9f\x98\x9b";
  emoji["flushed"]="\xf0\x9f\x98\xb3";
  emoji["grin"]="\xf0\x9f\x98\x81";
  emoji["pensive"]="\xf0\x9f\x98\x94";
  emoji["relieved"]="\xf0\x9f\x98\x8c";
  emoji["unamused"]="\xf0\x9f\x98\x92";
  emoji["disappointed"]="\xf0\x9f\x98\x9e";
  emoji["persevere"]="\xf0\x9f\x98\xa3";
  emoji["cry"]="\xf0\x9f\x98\xa2";
  emoji["joy"]="\xf0\x9f\x98\x82";
  emoji["sob"]="\xf0\x9f\x98\xad";
  emoji["sleepy"]="\xf0\x9f\x98\xaa";
  emoji["disappointed_relieved"]="\xf0\x9f\x98\xa5";
  emoji["cold_sweat"]="\xf0\x9f\x98\xb0";
  emoji["sweat_smile"]="\xf0\x9f\x98\x85";
  emoji["sweat"]="\xf0\x9f\x98\x93";
  emoji["weary"]="\xf0\x9f\x98\xa9";
  emoji["tired_face"]="\xf0\x9f\x98\xab";
  emoji["fearful"]="\xf0\x9f\x98\xa8";
  emoji["scream"]="\xf0\x9f\x98\xb1";
  emoji["angry"]="\xf0\x9f\x98\xa0";
  emoji["rage"]="\xf0\x9f\x98\xa1";
  emoji["triumph"]="\xf0\x9f\x98\xa4";
  emoji["confounded"]="\xf0\x9f\x98\x96";
  emoji["laughing"]="\xf0\x9f\x98\x86";
  emoji["yum"]="\xf0\x9f\x98\x8b";
  emoji["mask"]="\xf0\x9f\x98\xb7";
  emoji["sunglasses"]="\xf0\x9f\x98\x8e";
  emoji["sleeping"]="\xf0\x9f\x98\xb4";
  emoji["dizzy_face"]="\xf0\x9f\x98\xb5";
  emoji["astonished"]="\xf0\x9f\x98\xb2";
  emoji["worried"]="\xf0\x9f\x98\x9f";
  emoji["frowning"]="\xf0\x9f\x98\xa6";
  emoji["anguished"]="\xf0\x9f\x98\xa7";
  emoji["smiling_imp"]="\xf0\x9f\x98\x88";
  emoji["imp"]="\xf0\x9f\x91\xbf";
  emoji["open_mouth"]="\xf0\x9f\x98\xae";
  emoji["grimacing"]="\xf0\x9f\x98\xac"
  emoji["neutral_face"]="\xf0\x9f\x98\x90";
  emoji["confused"]="\xf0\x9f\x98\x95";
  emoji["hushed"]="\xf0\x9f\x98\xaf";
  emoji["no_mouth"]="\xf0\x9f\x98\xb6";
  emoji["innocent"]="\xf0\x9f\x98\x87";
  emoji["smirk"]="\xf0\x9f\x98\x8f";
  emoji["expressionless"]="\xf0\x9f\x98\x91";
  emoji["man_with_gua_pi_mao"]="\xf0\x9f\x91\xb2";
  emoji["man_with_turban"]="\xf0\x9f\x91\xb3";
  emoji["cop"]="\xf0\x9f\x91\xae";
  emoji["construction_worker"]="\xf0\x9f\x91\xb7";
  emoji["guardsman"]="\xf0\x9f\x92\x82";
  emoji["baby"]="\xf0\x9f\x91\xb6";
  emoji["boy"]="\xf0\x9f\x91\xa6";
  emoji["girl"]="\xf0\x9f\x91\xa7";
  emoji["man"]="\xf0\x9f\x91\xa8";
  emoji["woman"]="\xf0\x9f\x91\xa9";
  emoji["older_man"]="\xf0\x9f\x91\xb4";
  emoji["older_woman"]="\xf0\x9f\x91\xb5";
  emoji["person_with_blond_hair"]="\xf0\x9f\x91\xb1";
  emoji["angel"]="\xf0\x9f\x91\xbc";
  emoji["princess"]="\xf0\x9f\x91\xb8";
  emoji["smiley_cat"]="\xf0\x9f\x98\xba";
  emoji["smile_cat"]="\xf0\x9f\x98\xb8";
  emoji["heart_eyes_cat"]="\xf0\x9f\x98\xbb";
  emoji["kissing_cat"]="\xf0\x9f\x98\xbd";
  emoji["smirk_cat"]="\xf0\x9f\x98\xbc";
  emoji["scream_cat"]="\xf0\x9f\x99\x80";
  emoji["crying_cat_face"]="\xf0\x9f\x98\xbf";
  emoji["joy_cat"]="\xf0\x9f\x98\xb9";
  emoji["pouting_cat"]="\xf0\x9f\x98\xbe";
  emoji["japanese_ogre"]="\xf0\x9f\x91\xb9";
  emoji["japanese_goblin"]="\xf0\x9f\x91\xba";
  emoji["see_no_evil"]="\xf0\x9f\x99\x88";
  emoji["hear_no_evil"]="\xf0\x9f\x99\x89";
  emoji["speak_no_evil"]="\xf0\x9f\x99\x8a";
  emoji["skull"]="\xf0\x9f\x92\x80";
  emoji["alien"]="\xf0\x9f\x91\xbd";
  emoji["poo"]="\xf0\x9f\x92\xa9";
  emoji["fire"]="\xf0\x9f\x94\xa5";
  emoji["sparkles"]="\xe2\x9c\xa8";
  emoji["glowing_star"]="\xf0\x9f\x8c\x9f";
  emoji["dizzy"]="\xf0\x9f\x92\xab";
  emoji["boom"]="\xf0\x9f\x92\xa5";
  emoji["anger"]="\xf0\x9f\x92\xa2";
  emoji["sweat_drops"]="\xf0\x9f\x92\xa6";
  emoji["droplet"]="\xf0\x9f\x92\xa7";
  emoji["zzz"]="\xf0\x9f\x92\xa4";
  emoji["dash"]="\xf0\x9f\x92\xa8";
  emoji["ear"]="\xf0\x9f\x91\x82";
  emoji["eyes"]="\xf0\x9f\x91\x80";
  emoji["nose"]="\xf0\x9f\x91\x83";
  emoji["tongue"]="\xf0\x9f\x91\x85";
  emoji["mouth"]="\xf0\x9f\x91\x84";
  emoji["ok_hand"]="\xf0\x9f\x91\x8c";
  emoji["facepunch"]="\xf0\x9f\x91\x8a";
  emoji["fist"]="\xe2\x9c\x8a";
  emoji["v"]="\xe2\x9c\x8c\xef\xb8\x8f";
  emoji["wave"]="\xf0\x9f\x91\x8b";
  emoji["hand"]="\xe2\x9c\x8b";
  emoji["open_hands"]="\xf0\x9f\x91\x90";
  emoji["point_down"]="\xf0\x9f\x91\x87";
  emoji["point_right"]="\xf0\x9f\x91\x89";
  emoji["point_left"]="\xf0\x9f\x91\x88";
  emoji["raised_hands"]="\xf0\x9f\x99\x8c";
  emoji["pray"]="\xf0\x9f\x99\x8f";
  emoji["point_up"]="\xe2\x98\x9d\xef\xb8\x8f";
  emoji["clap"]="\xf0\x9f\x91\x8f";
  emoji["muscle"]="\xf0\x9f\x92\xaa";
  emoji["walking"]="\xf0\x9f\x9a\xb6";
  emoji["runner"]="\xf0\x9f\x8f\x83";
  emoji["dancer"]="\xf0\x9f\x92\x83";
  emoji["couple"]="\xf0\x9f\x91\xab";
  emoji["family"]="\xf0\x9f\x91\xaa";
  emoji["two_men_holding_hands"]="\xf0\x9f\x91\xac";
  emoji["two_women_holding_hands"]="\xf0\x9f\x91\xad";
  emoji["couple_kiss"]="\xf0\x9f\x92\x8f";
  emoji["couple_with_heart"]="\xf0\x9f\x92\x91";
  emoji["dancers"]="\xf0\x9f\x91\xaf";
  emoji["ok_woman"]="\xf0\x9f\x99\x86";
  emoji["no_good"]="\xf0\x9f\x99\x85";
  emoji["information_desk_person"]="\xf0\x9f\x92\x81";
  emoji["raising_hand"]="\xf0\x9f\x99\x8b";
  emoji["massage"]="\xf0\x9f\x92\x86";
  emoji["haircut"]="\xf0\x9f\x92\x87";
  emoji["nail_polish"]="\xf0\x9f\x92\x85";
  emoji["bride_with_veil"]="\xf0\x9f\x91\xb0";
  emoji["person_with_pouting_face"]="\xf0\x9f\x99\x8e";
  emoji["person_frowning"]="\xf0\x9f\x99\x8d";
  emoji["bow"]="\xf0\x9f\x99\x87";
  emoji["tophat"]="\xf0\x9f\x8e\xa9";
  emoji["crown"]="\xf0\x9f\x91\x91";
  emoji["womans_hat"]="\xf0\x9f\x91\x92";
  emoji["athletic_shoe"]="\xf0\x9f\x91\x9f";
  emoji["mans_shoe"]="\xf0\x9f\x91\x9e";
  emoji["sandal"]="\xf0\x9f\x91\xa1";
  emoji["high_heel"]="\xf0\x9f\x91\xa0";
  emoji["boot"]="\xf0\x9f\x91\xa2";
  emoji["shirt"]="\xf0\x9f\x91\x95";
  emoji["necktie"]="\xf0\x9f\x91\x94";
  emoji["womans_clothes"]="\xf0\x9f\x91\x9a";
  emoji["dress"]="\xf0\x9f\x91\x97";
  emoji["running_shirt_with_sash"]="\xf0\x9f\x8e\xbd";
  emoji["jeans"]="\xf0\x9f\x91\x96";
  emoji["kimono"]="\xf0\x9f\x91\x98";
  emoji["bikini"]="\xf0\x9f\x91\x99";
  emoji["briefcase"]="\xf0\x9f\x92\xbc";
  emoji["handbag"]="\xf0\x9f\x92\xbc";
  emoji["pouch"]="\xf0\x9f\x91\x9d";
  emoji["purse"]="\xf0\x9f\x91\x9b";
  emoji["eyeglasses"]="\xf0\x9f\x91\x93";
  emoji["ribbon"]="\xf0\x9f\x8e\x80";
  emoji["closed_umbrella"]="\xf0\x9f\x8c\x82";
  emoji["lipstick"]="\xf0\x9f\x92\x84";
  emoji["yellow_heart"]="\xf0\x9f\x92\x9b";
  emoji["blue_heart"]="\xf0\x9f\x92\x99";
  emoji["purple_heart"]="\xf0\x9f\x92\x9c";
  emoji["green_heart"]="\xf0\x9f\x92\x9a";
  emoji["heart"]="\xe2\x9d\xa4\xef\xb8\x8f";
  emoji["broken_heart"]="\xf0\x9f\x92\x94";
  emoji["heartpulse"]="\xf0\x9f\x92\x97";
  emoji["heartbeat"]="\xf0\x9f\x92\x93";
  emoji["two_hearts"]="\xf0\x9f\x92\x95";
  emoji["sparkling_heart"]="\xf0\x9f\x92\x96";
  emoji["revolving_hearts"]="\xf0\x9f\x92\x9e";
  emoji["cupid"]="\xf0\x9f\x92\x98";
  emoji["love_letter"]="\xf0\x9f\x92\x8c";
  emoji["kiss"]="\xf0\x9f\x92\x8b";
  emoji["ring"]="\xf0\x9f\x92\x8d";
  emoji["gem"]="\xf0\x9f\x92\x8e";
  emoji["bust_in_silhouette"]="\xf0\x9f\x91\xa4";
  emoji["busts_in_silhouette"]="\xf0\x9f\x91\xa5";
  emoji["speech_balloon"]="\xf0\x9f\x92\xac";
  emoji["footprints"]="\xf0\x9f\x91\xa3";
  emoji["thought_balloon"]="\xf0\x9f\x92\xad";
  emoji["dog"]="\xf0\x9f\x90\xb6";
  emoji["wolf"]="\xf0\x9f\x90\xba";
  emoji["cat"]="\xf0\x9f\x90\xb1";
  emoji["mouse"]="\xf0\x9f\x90\xad";
  emoji["hamster"]="\xf0\x9f\x90\xb9";
  emoji["rabbit"]="\xf0\x9f\x90\xb0";
  emoji["frog"]="\xf0\x9f\x90\xb8";
  emoji["tiger"]="\xf0\x9f\x90\xaf";
  emoji["koala"]="\xf0\x9f\x90\xa8";
  emoji["bear"]="\xf0\x9f\x90\xbb";
  emoji["pig"]="\xf0\x9f\x90\xb7";
  emoji["pig_nose"]="\xf0\x9f\x90\xbd";
  emoji["cow"]="\xf0\x9f\x90\xae";
  emoji["boar"]="\xf0\x9f\x90\x97";
  emoji["monkey_face"]="\xf0\x9f\x90\xb5";
  emoji["monkey"]="\xf0\x9f\x90\x92";
  emoji["horse"]="\xf0\x9f\x90\xb4";
  emoji["sheep"]="\xf0\x9f\x90\x91";
  emoji["elephant"]="\xf0\x9f\x90\x98";
  emoji["panda_face"]="\xf0\x9f\x90\xbc";
  emoji["penguin"]="\xf0\x9f\x90\xa7";
  emoji["bird"]="\xf0\x9f\x90\xa6";
  emoji["baby_chick"]="\xf0\x9f\x90\xa4";
  emoji["hatched_chick"]="\xf0\x9f\x90\xa5";
  emoji["hatching_chick"]="\xf0\x9f\x90\xa3";
  emoji["chicken"]="\xf0\x9f\x90\x94";
  emoji["snake"]="\xf0\x9f\x90\x8d";
  emoji["turtle"]="\xf0\x9f\x90\xa2";
  emoji["bug"]="\xf0\x9f\x90\x9b";
  emoji["bee"]="\xf0\x9f\x90\x9d";
  emoji["ant"]="\xf0\x9f\x90\x9c";
  emoji["beetle"]="\xf0\x9f\x90\x9e";
  emoji["snail"]="\xf0\x9f\x90\x8c";
  emoji["octopus"]="\xf0\x9f\x90\x99";
  emoji["shell"]="\xf0\x9f\x90\x9a";
  emoji["tropical_fish"]="\xf0\x9f\x90\xa0";
  emoji["fish"]="\xf0\x9f\x90\x9f";
  emoji["dolphin"]="\xf0\x9f\x90\xac";
  emoji["whale"]="\xf0\x9f\x90\xb3";
  emoji["ram"]="\xf0\x9f\x90\x8f";
  emoji["rat"]="\xf0\x9f\x90\x80";
  emoji["water_buffalo"]="\xf0\x9f\x90\x83";



  emoji["cloud"]="\xe2\x98\x81\xef\xb8\x8f";
  emoji["sunny"]="\xe2\x98\x80\xef\xb8\x8f";
  emoji["airplane"]="\xe2\x9c\x88\xef\xb8\x8f";
  emoji["deciduous_tree"]="\xf0\x9f\x8c\xb3";
  emoji["evergreen_tree"]="\xf0\x9f\x8c\xb2";
  emoji["oncoming_police_car"]="\xf0\x9f\x9a\x94";
  emoji["oncoming_automobile"]="\xf0\x9f\x9a\x98";
}

function is_emoji(emoji_name)
{
  return emoji[emoji_name] != "";
}


function match_emoji(string)
{
  match($0, /\:[a-z_\+1]+\:/) ;
  emoji_name = substr($0, RSTART+1, RLENGTH-2);
  if ( is_emoji(emoji_name) ) {
    return emoji_name;
  } else {
    return 0;
  }
}

function replace_emoji(string, emoji_name)
{
  emoji_char = emoji[emoji_name] " ";
  substitution = ":" emoji_name ":"
  gsub(substitution, emoji_char, string);
  return string;
}

{
  emoji_name = match_emoji($0);
  while(emoji_name != 0) {
    $0 = replace_emoji($0, emoji_name)
    emoji_name = match_emoji($0);
  }
  print $0;
}
